### ISSUE TITLE
Notice and Warning related to $end_user_obj

### ISSUE THREAD

**Issue by obicke** [fusionx1/terminus-get-newrelic#11]
`PHP Notice:  Undefined index: end_user_summary in /root/.terminus/plugins/terminus-newrelic-data-plugin-2.0.1/src/Commands/GetNewrelicCommand.php on line 368`

and 

`PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /root/.terminus/plugins/terminus-newrelic-data-plugin-2.0.1/src/Commands/GetNewrelicCommand.php on line 380`

**Comment by fusionx1** [comment]
This has been fixed and we may need to phase out this repo in favor of https://github.com/pantheon-systems/terminus-newrelic-data-plugin.
